### ISSUE TITLE
Record playlist JS1 Week 4

### ISSUE THREAD

**Issue by Dedekind561** [CodeYourFuture/JavaScript-Core-1-Coursework-Week4-London8#199]
Contents
[Array properties](https://syllabus.codeyourfuture.io/js-core-1/week-4/lesson#array-properties)
[Manipulating arrays](https://syllabus.codeyourfuture.io/js-core-1/week-4/lesson#manipulating-arrays)
[Array methods](https://syllabus.codeyourfuture.io/js-core-1/week-4/lesson#array-methods)
[Array map](https://syllabus.codeyourfuture.io/js-core-1/week-4/lesson#array-map)
[Array forEach](https://syllabus.codeyourfuture.io/js-core-1/week-4/lesson#array-foreach)
[Array filter](https://syllabus.codeyourfuture.io/js-core-1/week-4/lesson#array-find)
[Array find](https://syllabus.codeyourfuture.io/js-core-1/week-4/lesson#array-find)

**Comment by Dedekind561** [comment]
Maybe ask Zachee to help out with this open issue?

**Comment by gregdyke** [comment]
I think we have too many array methods in this week in the syllabus. Again, I would go for a "stretch video" (I notice this idea hasn't have any uptake so far - I'm a bit confused why?)

length and accessing is already done in week 3

Include:
- filter
- map
- function passing + think like a computer materials for how this works with filter, map etc.
- forEach .... maaaaybe? but it's not super useful compared to for ... of, except for chaining arr.filter.map.forEach

Stretch
- includes
- split
- find
- sort
- different ways of writing functions + anonymous functions? (or keep for JS2?)

Don't include
- slice
- splice
- concat
- join

**Comment by gregdyke** [comment]
There might be some nice CYF blocks connections to be drawn here (cyf blocks has for each and push isEmpty, getRandom element and sum - but the implementations of isEmpty and sum are unfortunately a bit arcane - `!arr.length`, `arr.reduce((a,b) => a+b, 0)`

**Comment by Dedekind561** [comment]
Sweet!
We can also use this 👉 https://array-visualizer.codeyourfuture.io/
